name: vamr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cycler==0.11.0
  - kiwisolver==1.4.4
  - matplotlib==3.5.3
  - packaging==21.3
  - Pillow==9.3.0
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - scipy==1.7.3
  - six==1.16.0
  - typing-extensions==4.4.0
  - pip
  - pip:
      - fonttools==4.38.0
      - numpy==1.26.2
      - opencv-python==4.6.0.66
      - pandas==2.1.4
      - tqdm==4.66.1
      - pyyaml==6.0.1
